### PR TITLE
Schema definition for start has been implemented

### PR DESCRIPTION
**Pull request by fuatsengul**
Hi!
I've added schema definition support for 'start' property.

### CODE REVIEW

**Comment by jimmiebtlr** [comment]
If I understand what you're trying to implement, it seems like you may have the check of `options.start` backward.  

I believe what you're trying to do is allow setting `start` to override the min/max settings of the schema, is this correct?

**Comment by fuatsengul** [comment]
Yes, that's all correct :)

**Comment by jimmiebtlr** [comment]
Would you mind resubmitting with 

`if( options.start == typeof(undefined) ){`

**Comment by jimmiebtlr** [comment]
I've made changes to allow defining start and range manually, in autoform options, noUiSlider options, or at the template level.

**Pull request closed without merging**
